### ISSUE TITLE
Error when installing Xdebug + VS Code in Local on Linux

### ISSUE THREAD

**Issue by perikorese** [pixeljar/local-addon-xdebug-vscode#6]
Local version 5.6.3+4270 on Linux Mint.

When I go to the Addons tab on Local and go to Xdebug + VS Code and click "INSTALL ADD-ON", I get this error after a while:

![Skærmbillede fra 2020-07-10 13-43-41](https://user-images.githubusercontent.com/52708770/87174769-f9078c00-c2d7-11ea-91b9-3b7cf6a127bf.png)

And the addon is not installed.

And here is what appears in local-lightning.log:

`{
    "thread": "main",
    "class": "",
    "errno": -18,
    "syscall": "rename",
    "code": "EXDEV",
    "path": "/tmp/local-BsyAMLjt-/package",
    "dest": "%%userDataPath%%/addons/local-addon-xdebug-vscode",
    "level": "error",
    "stack": "Error: EXDEV: cross-device link not permitted, rename '/tmp/local-BsyAMLjt-/package' -> '%%userDataPath%%/addons/local-addon-xdebug-vscode'\n    at Object.renameSync (fs.js:609:3)\n    at Object.moveSync [as sync] (%%appPath%%/node_modules/fs-jetpack/lib/move.js:27:8)\n    at Object.move (%%appPath%%/node_modules/fs-jetpack/lib/jetpack.js:179:12)\n    at exports.default.<anonymous> (%%appPath%%/main/addons/AddonInstallerService.js:1:6635)\n    at Generator.next (<anonymous>)\n    at o (%%appPath%%/main/addons/AddonInstallerService.js:1:124)",
    "message": "EXDEV: cross-device link not permitted, rename '/tmp/local-BsyAMLjt-/package' -> '%%userDataPath%%/addons/local-addon-xdebug-vscode'",
    "timestamp": "2020-07-10T16:12:42.051Z"
}`

**Comment by brandondove** [comment]
@perikorese thanks for pointing this out. I'll bring this to the Local team as the errors seem to indicate an issue with the installation process in Local on Linux. Are you able to install any of the other add-ons using the same process?

**Comment by brandondove** [comment]
@perikorese - here's a similar bug report on the Local forums - https://localwp.com/community/t/error-installing-add-on-on-linux/19244. I updated it with a link to this issue.

**Comment by perikorese** [comment]
@brandondove I tried installing the Notes addon and I get the same type of error.

**Comment by brandondove** [comment]
@perikorese that lines up with what I was thinking. As I said, I updated the post on their forums to see if we could get some attention on the issue. If you want to install the add-on manually, you can download this repository, decompress it, and place the `local-addon-xdebug-vscode` folder in `~/Library/Application Support/Local/addons`. Once you do that and restart Local it should show up in the installed add-ons area.

**Comment by afragen** [comment]
Check the latest release asset and see if it installs correctly. It does for me on MacOS.
